### ISSUE TITLE
question on iv->iv

### ISSUE THREAD

**Issue by jshen28** [nibrunie/af_alg-examples#2]
Hello and thank you very much for sharing demo. I got a small question towards the [code](https://github.com/nibrunie/af_alg-examples/blob/80b9e7f03d7f542b46748dd02cfc96ade47f37b4/examples/basic_cipher.c#L54) which sets up iv vector. My question is why `iv->iv` points to the data address? I suppose `iv` is from `cbuf` which is initialized to 0 so `iv->iv` should be 0 (but obviously my point is incorrect).

Thank you much for your help.

Best,
Jiatong Shen

**Comment by nibrunie** [comment]
Hello @jshen28 thank you for your interest.
I have to say, it has been a while since I looked at that code. I am sure you can find more up-to-date resources.
